---
Filesystem:
    filemanager: /usr/bin/sh
HabCam:
    imagepath: /home/jovyan/hbc_browser/data/imgs_jpg
    imagemetadata: /home/jovyan/hbc_browser/data/imagemetadata.pq
    imageannotation: /home/jovyan/hbc_browser/data/detector_output.csv
Mbes:
    soundings: /home/jovyan/hbc_browser/data/mbes_2015.parquet
Export:
    kmldir: /home/jovyan/hbc_browser/export/kml
Processing:
    GPU: False
    GRASS_API: http://localhost/docs
