---
Filesystem:
    filemanager: {{filemanager}}
HabCam:
    imagepath: {{imagepath}}
    imagemetadata: {{imagemetadata}}
    imageannotation: {{imageannotation}}
Mbes:
    soundings: {{soundings}}
Export:
    kmldir: {{kmldir}}
Processing:
    gpu_avaibility: {{gpu_avaibility}}
    grass_api_endpoint: {{grass_api_endpoint}}